CREATE TABLE IF NOT EXISTS usage_events (
    id SERIAL PRIMARY KEY,
    customer_id VARCHAR(100) NOT NULL,
    service VARCHAR(100) NOT NULL,
    quantity NUMERIC(12, 2) NOT NULL,
    unit VARCHAR(50) NOT NULL,
    event_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);